name: Validate with Hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
  test:
    name: Tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "astral-sh/setup-uv@v5"
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Lint
        run: |
          uvx ruff check .
          uvx ruff format --check .
      - name: Test
        run: uv run pytest
